name: Nodex Build
run-name: Build-Package
on: [push]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build-deb
        run: ./mkdeb.sh
        working-directory: ./.dpkg
      
      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: <draft>
          release_name: <draft>
          draft: true
          prerelease: false
        
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.dpkg/build/nodex.deb
          asset_name: nodex.deb
          asset_content_type: application/zip
      
      # UNCOMMENT TO PUBLISH
      # BETTER TO LEAVE THIS AS A DRAFT
      # AND HAVE A HUMAN PUBLISH
      # - uses: eregon/publish-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     release_id: ${{ steps.create_release.outputs.id }}
